sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) #assign git commit sha env var.
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 #disable google cloud cli prompts
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; #download & install gc sdk
  - source $HOME/google-cloud-sdk/path.bash.inc #modify shell for sdk use in shell
  - gcloud components update kubectl #install kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-298214
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  #Log into docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t test/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run test/react-test npm test -- --coverage #dummy tests

deploy:
  provider: script
  script: bash ./deploy.sh #Building & pushing images to docker hub
  on:
    branch: master