apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - port: 6379 #other pods in cluster access via port
      targetPort: 6379  #port on target object pod@component:redis(access is being provided to)
  selector:
    component: redis